services:
  - type: web
    name: nextapp
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    autoDeploy: true
    repo: https://github.com/elegantShock2258/multiplayer-wordle
    region: singapore 

  - type: web
    name: signalserver
    env: docker
    plan: free
    dockerfilePath: ./SignallingServer/Dockerfile
    autoDeploy: true
    repo: https://github.com/elegantShock2258/multiplayer-wordle
    region: singapore