services:
  - type: web
    name: nextapp
    env: node
    plan: free
    autoDeploy: true
    buildCommand: yarn install && yarn build
    startCommand: yarn start
  
    repo: https://github.com/elegantShock2258/multiplayer-wordle
    region: singapore 

  - type: web
    name: signalserver
    buildCommand: |
      yarn install
    startCommand: |
      yarn run local:server
    env: node
    plan: free
    autoDeploy: true
    repo: https://github.com/elegantShock2258/multiplayer-wordle
    region: singapore